name: PR Build
on:
  pull_request:
    branches:
      - "master"
      - "feature/**"
      - "fix/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up build environment
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build branch
        run: deploy/build-branch.sh
