name: PR Build
on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
  pull_request:
    branches:
      - "master"
      - "feature/**"
      - "fix/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up build environment
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "zulu"
          cache: maven
      - name: Build branch
        run: deploy/build-branch.sh
